<center>
    <h1>JaxTon</h1>
    <i>💯 JAX exercises</i>
    <br>
    <br>
    <a href='https://github.com/vopani/jaxton/blob/master/LICENSE'>
        <img src='https://img.shields.io/badge/license-Apache%202.0-blue.svg?logo=apache'>
    </a>
    <a href='https://github.com/vopani/jaxton'>
        <img src='https://img.shields.io/github/stars/vopani/jaxton?color=yellowgreen&logo=github'>
    </a>
    <a href='https://twitter.com/vopani'>
        <img src='https://img.shields.io/twitter/follow/vopani'>
    </a>
</center>

<center>
    This is Set 2: Data Operations (Exercises 11-20) of <b>JaxTon</b>: <i>💯 JAX exercises</i>
    <br>
    You can find all the exercises and solutions on <a href="https://github.com/vopani/jaxton#exercises-">GitHub</a>
</center>

**Prerequisites**

* Run the setup cells below before starting the exercises.

In [1]:
## install or upgrade jax
!python3 -m pip install -U jax

In [2]:
## import packages
import jax
import jax.numpy as jnp

jax.devices()

[CpuDevice(id=0)]

**Exercise 11: Create a matrix with values [[10, 1, 24], [20, 15, 14]] and assign it to `data`**

In [13]:
data = jnp.array([[10, 1, 24], [20, 15, 14]])
data

Array([[10,  1, 24],
       [20, 15, 14]], dtype=int32)

**Exercise 12: Assign the transpose of `data` to `dataT`**

In [14]:
dataT = data.T

**Exercise 13: Assign the element of `data` at index [0, 2] to `value`**

In [15]:
value = data[0, 2]

**Exercise 14: Update the value of `data` at index [1, 1] to `100`**

In [16]:
data = data.at[1, 1].set(100)

**Exercise 15: Add `41` to the value of `data` at index [0, 0]**

In [17]:
data = data.at[0, 0].add(41)

**Exercise 16: Calculate the minimum values over axis=1 and assign it to `mins`**

In [18]:
mins = data.min(axis=1)
mins

Array([ 1, 14], dtype=int32)

**Exercise 17: Select the first row of values of `data` and assign it to `data_select`**

In [19]:
data_select = data[0, :]
data_select

Array([51,  1, 24], dtype=int32)

**Exercise 18: Append the row `data_select` to `data`**

In [25]:
data = jnp.concat([data, data_select[None, :]], axis=0)
data

Array([[ 51,   1,  24],
       [ 20, 100,  14],
       [ 51,   1,  24],
       [ 51,   1,  24]], dtype=int32)

**Exercise 19: Multiply the matrices `data` and `dataT` and assign it to `data_prod`**

In [26]:
data_prod = data @ dataT

**Exercise 20: Convert the dtype of `data_prod` to `float32`**

In [27]:
data_prod = data_prod.astype(jnp.float32)

<center>
    This completes Set 2: Data Operations (Exercises 11-20) of <b>JaxTon</b>: <i>💯 JAX exercises</i>
    <br>
    You can find all the exercises and solutions on <a href="https://github.com/vopani/jaxton#exercises-">GitHub</a>
</center>