<center>
    <h1>JaxTon</h1>
    <i>💯 JAX exercises</i>
    <br>
    <br>
    <a href='https://github.com/vopani/jaxton/blob/master/LICENSE'>
        <img src='https://img.shields.io/badge/license-Apache%202.0-blue.svg?logo=apache'>
    </a>
    <a href='https://github.com/vopani/jaxton'>
        <img src='https://img.shields.io/github/stars/vopani/jaxton?color=yellowgreen&logo=github'>
    </a>
    <a href='https://twitter.com/vopani'>
        <img src='https://img.shields.io/twitter/follow/vopani'>
    </a>
</center>

<center>
    This is Set 7: Automatic Vectorization (Exercises 61-70) of <b>JaxTon</b>: <i>💯 JAX exercises</i>
    <br>
    You can find all the exercises and solutions on <a href="https://github.com/vopani/jaxton#exercises-">GitHub</a>
</center>

**Prerequisites**

* Run the setup cells below before starting the exercises.
* Sample vectors and scoring functions will be used for the exercises.

In [ ]:
## install or upgrade jax
!python3 -m pip install -U jax

In [1]:
import jax
import jax.numpy as jnp

jax.devices()

[CpuDevice(id=0)]

In [2]:
## sample batch data
score_data = jnp.array([[3., 1., 2.], [6., 2., 4.], [9., 3., 6.]])
weights = jnp.array([0.2, 0.3, 0.5])
points_a = jnp.array([[0., 0.], [1., 1.], [2., 0.]])
points_b = jnp.array([[1., 0.], [2., 2.]])

score_data

Array([[3., 1., 2.],
       [6., 2., 4.],
       [9., 3., 6.]], dtype=float32)

In [3]:
## sample scoring functions
def normalize_row(row):
    return row / jnp.sum(row)

def weighted_score(row, weights):
    return jnp.sum(row * weights)

def distance(point_a, point_b):
    return jnp.sqrt(jnp.sum((point_a - point_b) ** 2))

**Exercise 61: Vectorize `normalize_row` over the rows of `score_data` and assign it to `normalize_rows`**

In [4]:
normalize_rows = jax.vmap(normalize_row)

**Exercise 62: Run `normalize_rows` on `score_data` and assign it to `normalized_scores`**

In [5]:
normalized_scores = normalize_rows(score_data)
normalized_scores

Array([[0.5       , 0.16666667, 0.33333334],
       [0.5       , 0.16666667, 0.33333334],
       [0.5       , 0.16666667, 0.33333334]], dtype=float32)

**Exercise 63: Vectorize `weighted_score` over rows while sharing `weights` and assign it to `batched_weighted_score`**

In [6]:
batched_weighted_score = jax.vmap(weighted_score, in_axes=(0, None))

**Exercise 64: Run `batched_weighted_score` on `score_data` and `weights` and assign it to `weighted_scores`**

In [7]:
weighted_scores = batched_weighted_score(score_data, weights)
weighted_scores

Array([1.9000001, 3.8000002, 5.7      ], dtype=float32)

**Exercise 65: Vectorize `distance` over `points_b` for a single point in `points_a` and assign it to `distances_to_b`**

In [9]:
distances_to_b = jax.vmap(distance, in_axes=(None, 0))

**Exercise 66: Run `distances_to_b` with the first point of `points_a` and assign it to `first_point_distances`**

In [11]:
first_point_distances = distances_to_b(points_a[0], points_b)
first_point_distances

Array([1.      , 2.828427], dtype=float32)

**Exercise 67: Create a pairwise distance function for `points_a` and `points_b` using nested vectorization and assign it to `pairwise_distances`**

In [12]:
pairwise_distances = jax.vmap(distances_to_b, in_axes=(0, None))

**Exercise 68: Run `pairwise_distances` on `points_a` and `points_b` and assign it to `distance_matrix`**

In [13]:
pairwise_distances(points_a, points_b)

Array([[1.       , 2.828427 ],
       [1.       , 1.4142135],
       [1.       , 2.       ]], dtype=float32)

**Exercise 69: Vectorize `normalize_row` over rows and place the mapped axis at axis=1, assigning it to `normalize_rows_columns`**

In [17]:
normalize_rows_columns = jax.vmap(normalize_row, in_axes=(0), out_axes=(1))

**Exercise 70: Run `normalize_rows_columns` on `score_data` and assign it to `normalized_scores_columns`**

In [18]:
normalized_scores_columns = normalize_rows_columns(score_data)
normalized_scores_columns

Array([[0.5       , 0.5       , 0.5       ],
       [0.16666667, 0.16666667, 0.16666667],
       [0.33333334, 0.33333334, 0.33333334]], dtype=float32)

<center>
    This completes Set 7: Automatic Vectorization (Exercises 61-70) of <b>JaxTon</b>: <i>💯 JAX exercises</i>
    <br>
    You can find all the exercises and solutions on <a href="https://github.com/vopani/jaxton#exercises-">GitHub</a>
</center>